CREATE TABLE "event-manage_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event-manage_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "event-manage_user" (
	"id" varchar PRIMARY KEY NOT NULL,
	"user_id" varchar(10) NOT NULL,
	"email" varchar(256) NOT NULL,
	"first_name" varchar(256) NOT NULL,
	"last_name" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "event-manage_user_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE INDEX "name_idx" ON "event-manage_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "event-manage_user" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "email_idx" ON "event-manage_user" USING btree ("email");